# -*- coding: utf-8 -*-
"""EXIST2024_Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T67HrrQo9gpvoosNAbzqM3xgWMMefgCM
"""

!pip install accelerate

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/University/Research/EXIST 2024

import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from transformers import pipeline, XLMRobertaTokenizer, XLMRobertaForSequenceClassification, AutoTokenizer, AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from sklearn.metrics import classification_report
from tqdm import tqdm
import numpy as np
import random

# Commented out IPython magic to ensure Python compatibility.
GLOBAL_SEED = 255

np.random.seed(GLOBAL_SEED)
random.seed(GLOBAL_SEED)
torch.manual_seed(GLOBAL_SEED)
torch.use_deterministic_algorithms(True)
# %env CUBLAS_WORKSPACE_CONFIG=:4096:8

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

train_df = pd.read_json('./Data/EXIST 2024 Tweets Dataset/training/EXIST2024_training.json').transpose()
dev_df = pd.read_json('./Data/EXIST 2024 Tweets Dataset/dev/EXIST2024_dev.json').transpose()
test_df = pd.read_json('./Data/EXIST 2024 Tweets Dataset/test/EXIST2023_test_clean.json').transpose()

label2id = {'NO': 0, 'DIRECT': 1, 'REPORTED': 2, 'JUDGEMENTAL': 3}
id2label = {0: 'NO', 1: 'DIRECT', 2: 'REPORTED', 3: 'JUDGEMENTAL'}

def preprocess(df):
  if 'predicted_label' not in df.columns:
    df['predicted_label'] = df['labels_task2'].apply(lambda x: np.argmax([x.count('-'), x.count('DIRECT'), x.count('REPORTED'), x.count('JUDGEMENTAL')]))
  for column_name in ['number_annotators', 'annotators', 'gender_annotators', 'age_annotators', 'ethnicities_annotators', 'study_levels_annotators', 'countries_annotators', 'split']:
    if column_name in df.columns:
      df.drop(column_name, axis=1, inplace=True)
  return df

train_df = preprocess(train_df)
dev_df = preprocess(dev_df)

train_df

class CustomDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=self.max_len,
            return_token_type_ids=False,
            padding='max_length',
            return_attention_mask=True,
            return_tensors='pt',
            truncation=True
        )
        return {
            'text': text,
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

def load_model_and_tokenizer(model_name, number_of_labels):
  # Initialize tokenizer and model
  tokenizer = AutoTokenizer.from_pretrained(model_name)
  #model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels = number_of_labels, device_map = 'auto')
  model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels = number_of_labels)

  return model, tokenizer

def train_model(model, tokenizer, train_df, val_df, id2label, batch_size = 8, number_of_epochs = 3, learning_rates = [1e-5, 1e-5, 1e-5], weight_decay = 0.01):

  #save the best model based on accuracy on dev set
  best_model = model
  best_dev_loss = np.inf

  # Move the model to GPU
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model.to(device)

  # Create datasets and dataloaders
  train_dataset = CustomDataset(train_df['tweet'].values, train_df['predicted_label'].values, tokenizer)
  val_dataset = CustomDataset(val_df['tweet'].values, val_df['predicted_label'].values, tokenizer)

  train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
  val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

  # Training loop (optional if you have labeled data)
  # Skip this part if you're doing zero-shot learning

  # Define early stopping
  best_val_loss = np.Inf
  patience = 3
  early_stopping_counter = 0

  # Train the model
  for epoch in range(number_of_epochs):
      # Define optimizer and loss function
      optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rates[epoch], weight_decay=weight_decay)
      total_steps = len(train_dataloader) * number_of_epochs
      scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=0, num_training_steps=total_steps)
      model.train()
      total_train_loss = 0
      total_train_correct = 0
      total_train_samples = 0

      for batch in tqdm(train_dataloader):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        total_train_loss += loss.item()

        preds = torch.argmax(outputs.logits, dim=1)
        total_train_correct += (preds == labels).sum().item()
        total_train_samples += labels.shape[0]

        loss.backward()
        optimizer.step()
        scheduler.step()

      train_loss = total_train_loss / len(train_dataloader)
      train_acc = total_train_correct / total_train_samples


      # Evaluation for this epoch
      model.eval()
      val_losses = []
      total_dev_loss = 0
      total_dev_correct = 0
      total_dev_samples = 0

      for batch in tqdm(val_dataloader):
          input_ids = batch['input_ids'].to(device)
          attention_mask = batch['attention_mask'].to(device)
          labels = batch['labels'].to(device)

          with torch.no_grad():
              outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
              val_losses.append(outputs.loss.item())

          loss = outputs.loss
          total_dev_loss += loss.item()

          preds = torch.argmax(outputs.logits, dim=1)
          total_dev_correct += (preds == labels).sum().item()
          total_dev_samples += labels.shape[0]

      avg_val_loss = np.mean(val_losses)

      dev_loss = total_dev_loss / len(val_dataloader)
      dev_acc = total_dev_correct / total_dev_samples

      if dev_loss < best_dev_loss:
        best_model = model
        best_dev_loss = dev_loss

      print(f'Epoch {epoch+1}/{number_of_epochs}')
      print(f'Train loss {train_loss}, accuracy {train_acc}')
      print(f'Dev loss {dev_loss}, accuracy {dev_acc}')

  # Load the best model
  return best_model, model, tokenizer

def Evaluate(model, tokenizer, val_df, id2label, batch_size = 8):

  # Move the model to GPU
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model.to(device)

  # Create datasets and dataloaders
  val_dataset = CustomDataset(val_df['tweet'].values, val_df['predicted_label'].values, tokenizer)

  val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

  # Evaluation
  model.eval()
  all_preds = []
  all_labels = []

  for batch in val_dataloader:
      input_ids = batch['input_ids'].to(device)
      attention_mask = batch['attention_mask'].to(device)
      labels = batch['labels'].to(device)

      with torch.no_grad():
          outputs = model(input_ids, attention_mask=attention_mask, labels=labels)

      logits = outputs.logits
      preds = torch.argmax(logits, dim=1).cpu().numpy()

      all_preds.extend(preds)
      all_labels.extend(labels.cpu().numpy())

  # Convert numerical labels back to text labels
  predicted_labels = [id2label[label] for label in all_preds]
  true_labels = [id2label[label] for label in all_labels]

  # Print classification report
  print(classification_report(true_labels, predicted_labels))
  return predicted_labels

from google.colab import userdata

def login2HF():
  !huggingface-cli login --token '{userdata.get('HF_token')}'

login2HF()

def save_and_upload(model, tokenizer, model_name2save):

  model.save_pretrained(model_name2save)
  tokenizer.save_pretrained(model_name2save)

"""## RoBerta"""

roberta_large_model, roberta_large_tokenizer = load_model_and_tokenizer('xlm-roberta-large', 4)
best_roberta_large_model, roberta_large_model, roberta_large_tokenizer = train_model(roberta_large_model, roberta_large_tokenizer, train_df, dev_df, id2label, batch_size=16, number_of_epochs=3, learning_rates=[2e-5, 1e-5, 1e-5], weight_decay=0.03)
predicted_labels = Evaluate(best_roberta_large_model, roberta_large_tokenizer, dev_df, id2label, batch_size = 16)

save_and_upload(roberta_large_model, roberta_large_tokenizer, 'EXIST2024_Task2_xlmRoberta_large_3_16')
!huggingface-cli upload 'EXIST2024_Task2_xlmRoberta_large_3_16'

roberta_large_model, roberta_large_tokenizer = load_model_and_tokenizer('am-azadi/EXIST2024_Task2_xlmRoberta_large_3_16', 4)
best_roberta_large_model, roberta_large_model, roberta_large_tokenizer = train_model(roberta_large_model, roberta_large_tokenizer, train_df, dev_df, id2label, batch_size=16, number_of_epochs=3, learning_rates=[5e-6, 2e-6, 1e-6], weight_decay=0.07)
predicted_labels = Evaluate(best_roberta_large_model, roberta_large_tokenizer, dev_df, id2label, batch_size = 16)

"""## mbert"""

mBert_model, mBert_tokenizer = train_model('bert-base-multilingual-cased', train_df, dev_df, 2, id2label, False, 3, 16)

"""# deberta model"""

deberta_v3_model, deberta_v3_tokenizer = train_model('microsoft/deberta-v3-base', train_df, dev_df, 2, id2label, False, 3, 16)

save_and_upload(deberta_v3_model, deberta_v3_tokenizer, 'EXIST2024_Task1_deberta_v3_3_16')
!huggingface-cli upload 'EXIST2024_Task1_deberta_v3_3_16'

deberta_v3_model, deberta_v3_tokenizer = train_model('am-azadi/EXIST2024_Task1_deberta_v3_3_16', train_df, dev_df, 2, id2label, False, 2, 16)

"""# PyEvALL"""

!pip install PyEvALL

from pyevall.evaluation import PyEvALLEvaluation
from pyevall.utils.utils import PyEvALLUtils

predictions = "./Data/evaluation/baselines/EXIST2024_dev_task1_majority_class_hard.json"
gold = "./Data/evaluation/golds/EXIST2024_dev_task1_gold_hard.json"
test = PyEvALLEvaluation()
params= dict()
params[PyEvALLUtils.PARAM_REPORT]= PyEvALLUtils.PARAM_OPTION_REPORT_EMBEDDED
metrics=["ICM", "ICMNorm" ,"FMeasure"]
report= test.evaluate(predictions, gold, metrics, **params)
report.print_report()

